
const API_BASE_URL = "https://aydin-unstandardised-nonerroneously.ngrok-free.dev";

export async function analyseQuery(data) {
  try {
    const response = await fetch(`${API_BASE_URL}/analyze`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'ngrok-skip-browser-warning': 'true' 
      },
      body: JSON.stringify({
        sql_query: data.query || "",     
        db_schema: data.schema || "",    
        db_size_info: data.dbSize || ""  
      }),
    });

    if (!response.ok) {
      const errData = await response.json();
      throw new Error(errData.detail || 'Failed to analyze query.');
    }

    const rawData = await response.json();


    return {
      syntax_valid: true,
      syntax_error: null,
      summary: rawData.is_already_optimal 
        ? "Query is already highly optimal." 
        : `Optimization required. Bottleneck severity is ${rawData.bottleneck_severity}.`,
      
      // ResultPanel expects a nested 'scores' object
      scores: {
        performance: rawData.performance_score || 0,
        readability: rawData.readability_score || 0,
        security: rawData.security_score || 0,
      },
      
      anti_patterns: (rawData.identified_anti_patterns || []).map(patternStr => ({
        pattern: "Detected Issue",
        severity: rawData.bottleneck_severity?.toLowerCase() || "medium",
        description: patternStr,
        suggestion: "Check the AI Explanation and Optimized SQL for the fix."
      })),
      
      index_recommendations: (rawData.recommended_indexes || []).map(idx => ({
        sql: idx.sql_statement,
        reason: idx.impact_justification
      })),
      
      explanation: rawData.detailed_explanation,
      optimized_query: rawData.optimized_sql,
      optimization_notes: "Generated by QueryLens AI.",
      complexity: rawData.bottleneck_severity,
      query_type: data.query.trim().split(' ')[0].toUpperCase() || "SELECT"
    };

  } catch (error) {
    console.error("API Request Error:", error);
    throw error;
  }
}

/**
 * Save analysis result to localStorage history
 */
export function saveToHistory(entry) {
  const history = getHistory()
  history.unshift({ ...entry, id: Date.now(), timestamp: new Date().toISOString() })
  const trimmed = history.slice(0, 20) // keep last 20
  localStorage.setItem('querylens_history', JSON.stringify(trimmed))
}

export function getHistory() {
  try {
    return JSON.parse(localStorage.getItem('querylens_history') || '[]')
  } catch {
    return []
  }
}

export function clearHistory() {
  localStorage.removeItem('querylens_history')
}
